#!/bin/bash
# Quick start script for TransVOD++ training on VisDrone

echo "==========================================="
echo "TransVOD++ VisDrone Training - Quick Start"
echo "==========================================="
echo ""
echo "✓ Dataset verified: 24,201 training images, 2,846 validation images"
echo "✓ 10 categories: pedestrian, people, bicycle, car, van, truck, tricycle, awning-tricycle, bus, motor"
echo "✓ Dataset loader created and tested successfully"
echo ""
echo "==========================================="
echo "Training Options:"
echo "==========================================="
echo ""
echo "Option 1: Train from scratch (NO COCO pretrained weights needed)"
echo "-----------------------------------------------------------------"
echo "cd /root/TemporalAttentionPlayground/TransVOD_plusplus"
echo "conda activate msda"
echo "GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 0 visdrone_scratch 1 configs/swinb_train_visdrone_single_scratch.sh"
echo ""
echo "Option 2: Train with COCO pretrained weights (RECOMMENDED - Better accuracy)"
echo "----------------------------------------------------------------------------"
echo "1. Download COCO pretrained Swin-B weights:"
echo "   ./download_coco_weights_instructions.sh"
echo ""
echo "2. Then run:"
echo "   cd /root/TemporalAttentionPlayground/TransVOD_plusplus"
echo "   conda activate msda"
echo "   GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 0 visdrone_swinb 1 configs/swinb_train_visdrone_single.sh"
echo ""
echo "==========================================="
echo "Multi-GPU Training (if you have multiple GPUs):"
echo "==========================================="
echo "GPUS_PER_NODE=4 ./tools/run_dist_launch.sh 0 visdrone_scratch 4 configs/swinb_train_visdrone_single_scratch.sh"
echo ""
echo "==========================================="
echo "Monitoring Training:"
echo "==========================================="
echo "Logs will be saved in: exps/visdrone_singlebaseline_swin_384_scratch/log.train.*"
echo "Checkpoints will be saved in: exps/visdrone_singlebaseline_swin_384_scratch/"
echo ""
echo "To monitor training progress:"
echo "  tail -f exps/visdrone_singlebaseline_swin_384_scratch/log.train.*"
echo ""
